infer_eval_metric: True
detect_and_drop_id_column: False
task_preprocessors_timeout: 3600
save_artifacts:
  enabled: False
  append_timestamp: True
  path: "./aga-artifacts"
feature_transformers:
  - _target_: autogluon_assistant.transformer.CAAFETransformer
    eval_model: lightgbm
    llm_provider: bedrock
    llm_model: "anthropic.claude-3-5-sonnet-20241022-v2:0"
    # llm_provider: openai
    # llm_model: gpt-4o-2024-08-06
    num_iterations: 5
    optimization_metric: roc
  - _target_: autogluon_assistant.transformer.OpenFETransformer
    n_jobs: 1
    num_features_to_keep: 10
  - _target_: autogluon_assistant.transformer.PretrainedEmbeddingTransformer
    model_name: 'all-mpnet-base-v2'
autogluon:
  predictor_init_kwargs: {}
  predictor_fit_kwargs:
    presets: best_quality
    time_limit: 14400
llm:
  # Note: bedrock is only supported in limited AWS regions
  provider: bedrock
  api_key_location: BEDROCK_API_KEY
  model: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  # provider: openai
  # api_key_location: OPENAI_API_KEY
  # model: gpt-4o-2024-08-06
  max_tokens: 512
  proxy_url: null
  temperature: 0
  verbose: True
