infer_eval_metric: True
detect_and_drop_id_column: False
task_preprocessors_timeout: 3600
save_artifacts:
  enabled: False
  append_timestamp: True
  path: "./aga-artifacts"
feature_transformers:
autogluon:
  predictor_init_kwargs: {}
  predictor_fit_kwargs:
    presets: medium_quality
    time_limit: 600
llm:
  # Note: bedrock is only supported in limited AWS regions
  #       and requires AWS credentials
  provider: bedrock
  model: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  # provider: openai
  # api_key_location: OPENAI_API_KEY
  # model: gpt-4o-2024-08-06
  max_tokens: 512
  proxy_url: null
  temperature: 0
  verbose: True
