[server]
maxUploadSize = 2048
enableStaticServing = true
[theme]
primaryColor="#4C7DE7"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#fbfcfc"
textColor="#404040"
font="serif"
[client]
showSidebarNavigation = false