[server]
maxUploadSize = 2048
enableStaticServing = true
[theme]
primaryColor="#4C7DE7"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#f8f9fa"
textColor="#000000"
font="serif"
[client]
showSidebarNavigation = false