name: "Test Assistant"
inputs:
  submodule-to-test:
    description: "The submodule to run tests against such as integration"
    required: true
  aws-role-arn:
    description: "AWS role ARN to assume"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: us-west-2
        role-duration-seconds: 1800
    
    - name: Run Tests
      shell: bash -l {0}
      run: |
        chmod +x ./.github/workflow_scripts/test_assistant.sh && ./.github/workflow_scripts/test_assistant.sh '${{ inputs.submodule-to-test }}'
