infer_eval_metric: True
feature_transformers:
  - _target_: autogluon_assistant.transformer.CAAFETransformer
    eval_model: lightgbm
    llm_model: gpt-3.5-turbo
    num_iterations: 2
    optimization_metric: roc
  - _target_: autogluon_assistant.transformer.OpenFETransformer
    n_jobs: 1
    num_features_to_keep: 10
autogluon:
  predictor_init_kwargs: {}
  predictor_fit_kwargs:
    verbosity: 2
    presets: best_quality 
    time_limit: 14400
    dynamic_stacking: False
    num_stack_levels: 0
llm:
  provider: openai
  api_key_location: OPENAI_API_KEY
  max_tokens: 512
  model: gpt-4-1106-preview
  # model: gpt-3.5-turbo
  proxy_url: null
  temperature: 0
  verbose: True