name: UI Test

on:
  push:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run UI Tests
        run: |
          chmod +x ./.github/workflow_scripts/test_ui.sh && ./.github/workflow_scripts/test_ui.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: ui-coverage
          path: ./ui_coverage.json
  run_coverage_check:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: ui-coverage-report
      - name: Run UI Unittests Coverage Check
        run: |
          chmod +x ./.github/workflow_scripts/test_ui_coverage.sh && ./.github/workflow_scripts/test_ui_coverage.sh
